### ISSUE TITLE
--help is not recognised as a command.

### ISSUE THREAD

**Issue by vincentdephily** [subamanis/mezura#2]
# Observed:

```
$ cargo run  -- . --help
Finished dev [unoptimized + debuginfo] target(s) in 0.01s
Running `target/debug/mezura ../md/ekko/backend/master/ --help`

--help is not recognised as a command.

Please provide a file name or a root directory path, and optional parameters.
Type --help for the parameter list
^C
$
```

# Expected
* The `--help` flag (an other flags should be recognized anywhere in the command line
* The binary should just `exit(1)` on error, not hang on until killed

**Comment by subamanis** [comment]
Thank you for reporting this.

The --help command was supposed to be used without any arguments, although admittedly, the error message in this case is pretty bad. 

Providing arguments to run the program and also providing the --help command is something you would not normally do, and I am not sure what should happen in this case, since the help message is pretty long, maybe the message should be displayed on the top, before the results.

The reason it doesn't die on error is because if you tried to run the program and you typed something incorrect you would probably want to try again. Although I might as well remove this behavior.

**Comment by vincentdephily** [comment]
Most programs will let you put `--help` anywhere. This is handy because you can just get your previous failed command and add `--help` at the end. It's not universally accepted, some CLIs are more nitpicky, but crates like `clap` handle this well.

Being able to re-enter the arguments in stdin if the given ones in CLI were wrong is... Weird. Just let people use the shell history to retry ;)

**Comment by subamanis** [comment]
Both of your observations have now been fixed in the latest release :)
